Repository DMWDGroup/ultraliga-analyst-service-node-vue, pull requests merged in 2019-11, with the labels that each got.

#30 C: Basic menu component
  UAS.Client/src/App.vue
  UAS.Client/src/components/TheMenu.vue
Labels: enhancement, frontend

#37 C: Ready source building Dockerfile config.
  UAS.Client/.dockerignore
  UAS.Client/Dockerfile
  UAS.Client/scripts/.gitkeep
Labels: CI/CD, devops, frontend

#39 C: Changed function declaration.
  UAS.Client/src/components/TheMenu.vue
Labels: frontend
